-- MySQL Script generated by MySQL Workbench
-- Wed Oct 11 14:04:51 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TallerCB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TallerCB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TallerCB` DEFAULT CHARACTER SET utf8 ;
USE `TallerCB` ;

-- -----------------------------------------------------
-- Table `TallerCB`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`usuarios` (
  `idUsusario` INT(18) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `fechNacimiento` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsusario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`clientes` (
  `cedula` INT(18) NOT NULL,
  `puntaje` INT(11) NULL DEFAULT NULL,
  `paginaWeb` VARCHAR(60) NULL DEFAULT NULL,
  `direcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`cedula`),
  CONSTRAINT `fk_clientes_usuarios1`
    FOREIGN KEY (`cedula`)
    REFERENCES `TallerCB`.`usuarios` (`idUsusario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`tipoproductos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`tipoproductos` (
  `idTipoProductos` INT(18) NOT NULL,
  `nombreTipoProducto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoProductos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`producto` (
  `idProducto` INT(18) NOT NULL,
  `idTipoProducto` INT(18) NULL DEFAULT NULL,
  `nombreProducto` VARCHAR(45) NULL DEFAULT NULL,
  `valorVenta` INT(18) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_TipoProducto_idx` (`idTipoProducto` ASC),
  CONSTRAINT `fk_TipoProducto`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `TallerCB`.`tipoproductos` (`idTipoProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`factura` (
  `numeroFactura` INT(18) NOT NULL,
  `idProducto` INT(18) NULL DEFAULT NULL,
  `idVendedor` INT(18) NULL DEFAULT NULL,
  `idCliente` INT(18) NULL DEFAULT NULL,
  `cantidad` INT(18) NULL DEFAULT NULL,
  `facturaVenta` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`numeroFactura`),
  INDEX `fk_factura_produc_idx` (`idProducto` ASC),
  INDEX `fk_vendedor_usu_idx` (`idVendedor` ASC),
  CONSTRAINT `fk_cliente_usu`
    FOREIGN KEY (`idProducto`)
    REFERENCES `TallerCB`.`usuarios` (`idUsusario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_produc`
    FOREIGN KEY (`idProducto`)
    REFERENCES `TallerCB`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_usu`
    FOREIGN KEY (`idVendedor`)
    REFERENCES `TallerCB`.`usuarios` (`idUsusario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`inventario` (
  `idProducto` INT(18) NOT NULL,
  `cantidad` INT(18) NULL DEFAULT NULL,
  `valor` INT(18) NULL DEFAULT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `fk_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `TallerCB`.`producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`sucursal` (
  `idSucursal` INT(18) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `direccion` VARCHAR(50) NULL DEFAULT NULL,
  `ciudad` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`idSucursal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TallerCB`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TallerCB`.`vendedor` (
  `Cedula` INT(18) NOT NULL,
  `idSucursal` INT(18) NULL DEFAULT NULL,
  `salario` VARCHAR(45) NULL DEFAULT NULL,
  INDEX `fk_vendedor_sucursal1_idx` (`idSucursal` ASC),
  PRIMARY KEY (`Cedula`),
  CONSTRAINT `fk_vendedor_sucursal`
    FOREIGN KEY (`idSucursal`)
    REFERENCES `TallerCB`.`sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vendedor_usuarios1`
    FOREIGN KEY (`Cedula`)
    REFERENCES `TallerCB`.`usuarios` (`idUsusario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
